# -*- coding: utf-8 -*-
"""Aula1_Introducao_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qVAze6mV3cJv_fLXH4mAVCMluCXkACEr
"""

print("Olá Mundo")

print("Estou aprendendo Python")

"Estou aprendendo Python"

1 + 1

10 - 2

#Esse é um comentário em Python

#Multiplicação
2 * 2

#Divisão
10/2

a = 4
b = 6

a + b

#Criando uma variável do tipo string
frase = "Python para análise de dados"

frase[0]

frase[0:10]

frase[10:]

frase[:17]

frase.count("dados")

frase.lower()

frase = frase.upper()

frase.replace("Python","Frases")

frase

