# -*- coding: utf-8 -*-
"""Aula1_Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vmdv6RA29XmgZjwczS1myHNJl9-QGQdC
"""

#importando a biblioteca pandas
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Learning_DIO_Curso_Python_Pandas_/datasets/Gapminder.csv", error_bad_lines=False, sep=";")

#Visualisando as 5 primeiras linhas
df.head()

df = df.rename(columns={"country": "Pais", "continent": "continente" , "year" : "Ano", "lifeExp" : "Expectativa de vida", "pop" : "Pop Total" , "gdpPercap" : "PIB" })

#Visualisando as 5 primeiras linhas
df.head(10)

#Total de linhas e colunas
df.shape

#Total de colunas
df.columns

#Total tipo de dado em cada coluna
df.dtypes

#Ultimas de linhas 
df.tail(15)

#TDescrição
df.describe()

#Filtro de valores unicos
df[ "continente" ] .unique()

#Filtro de localização especifica
Oceania = df.loc[df[ "continente" ]  == "Oceania" ]
Oceania.head()

#Filtro de localização especifica
Oceania [ "continente" ] .unique()

#Filtro de lAgrupamento de dados
df.groupby( "continente" )  ["Pais"] .nunique()

#Filtro de Expectativa de vida
df.groupby( "Ano" )  ["Expectativa de vida"] .mean()

#Filtro de PIB
df["PIB"] .mean()

#Filtro de  soma PIB
df["PIB"] .sum()

